# Generated by Django 4.2.30 on 2026-06-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(help_text='Código numérico de 2 dígitos para el ID del producto', max_length=2, unique=True, verbose_name='Código (2 dígitos)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Formato: 2 dígitos categoría + 6 dígitos producto (ej: 01000001)', max_length=8, unique=True, verbose_name='ID Producto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cover_image', models.ImageField(upload_to='products/covers/', verbose_name='Imagen principal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (€)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío si no está en oferta', max_digits=8, null=True, verbose_name='Precio rebajado (€)')),
                ('is_customizable', models.BooleanField(default=True, verbose_name='¿Personalizable?')),
                ('customization_options', models.TextField(blank=True, help_text='Colores disponibles, separados por coma', verbose_name='Opciones de personalización')),
                ('video_url', models.URLField(blank=True, verbose_name='URL del vídeo tutorial')),
                ('qr_code', models.ImageField(blank=True, upload_to='products/qr/', verbose_name='Código QR')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order'],
            },
        ),
    ]
