# Generated by Django 4.2.30 on 2026-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Unidades disponibles para vender', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Formato: 2 dígitos categoría + 4 dígitos producto (ej: 010001)', max_length=8, unique=True, verbose_name='ID Producto'),
        ),
    ]
