# Generated by Django 4.2.30 on 2026-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Formato: 2 dígitos categoría + 6 dígitos producto (ej: 01000001)', max_length=8, unique=True, verbose_name='ID Producto'),
        ),
    ]
