# Generated by Django 4.2.30 on 2026-06-03 17:45

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models._category_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(upload_to=apps.products.models._product_cover_path, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=apps.products.models._product_qr_path, verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models._product_gallery_path, verbose_name='Imagen'),
        ),
    ]
