# Generated by Django 4.2.30 on 2026-06-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del kit: materiales + patrón PDF + acceso vídeo tutorial', max_digits=8, null=True, verbose_name='Precio Pack DIY (€)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_diy_available',
            field=models.BooleanField(default=False, help_text='Si se activa, el cliente podrá comprar el kit de materiales + patrón + vídeo', verbose_name='¿Disponible como Pack DIY?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio pieza terminada (€)'),
        ),
    ]
