# Generated by Django 4.2.30 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_diy_price_product_is_diy_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_diy_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='diy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si tiene valor, el producto se ofrece como Pack DIY en la web', max_digits=8, null=True, verbose_name='Precio DIY (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio pieza (€)'),
        ),
    ]
