# Generated by Django 4.2.30 on 2026-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bizum', 'Bizum'), ('transfer', 'Transferencia bancaria'), ('card', 'Tarjeta de crédito')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
